### ISSUE TITLE
issues list view

### ISSUE THREAD

**Issue by phatpham9** [phatpham9/gitlab-one-board#2]
## list

- list all issues
- order by created date desc

### list item info

- title: [issue-id] [issue-title]
- asignee: asignee avatar
- repo: [repo-name]

### interaction

- clickable list item: link to the gitlab's issue page

**Comment by chauduong1192** [comment]
this issue has completed, please close it.

**Comment by phatpham9** [comment]
@chauduong1192 no we just had board view (kanban board) not list view. list view is a table with rows
